export const QUOTES = [
  // ── Augustine of Hippo ──────────────────────────────────────────────────────
  {
    id: 1,
    saint: "St. Augustine of Hippo",
    era: "4th–5th century AD",
    born: 354,
    died: 430,
    text: "Thou hast made us for thyself, O Lord, and our heart is restless until it finds its rest in thee.",
    textIt: "Ci hai fatti per te, Signore, e il nostro cuore è inquieto finché non trova riposo in te.",
    category: "Prayer",
    source: "Confessions, Book I, Chapter 1",
  },
  {
    id: 2,
    saint: "St. Augustine of Hippo",
    era: "4th–5th century AD",
    born: 354,
    died: 430,
    text: "Late have I loved thee, O Beauty so ancient and so new; late have I loved thee!",
    textIt: "Tardi ti ho amato, o Bellezza così antica e così nuova; ",
    category: "Love",
    source: "Confessions, Book X, Chapter 27",
  },
  {
    id: 3,
    saint: "St. Augustine of Hippo",
    era: "4th–5th century AD",
    born: 354,
    died: 430,
    text: "Love, and do what you will.",
    textIt: "Ama e fai ciò che vuoi.",
    category: "Love",
    source: "Homilies on the First Epistle of John, Tractate 7",
  },
  {
    id: 4,
    saint: "St. Augustine of Hippo",
    era: "4th–5th century AD",
    born: 354,
    died: 430,
    text: "Grant what Thou commandest, and command what Thou wilt.",
    textIt: "Concedi ciò che comandi e comanda ciò che vuoi.",
    category: "Prayer",
    source: "Confessions, Book X, Chapter 29",
  },
  {
    id: 5,
    saint: "St. Augustine of Hippo",
    era: "4th–5th century AD",
    born: 354,
    died: 430,
    text: "Faith is to believe what you do not see; the reward of this faith is to see what you believe.",
    textIt: "La fede è credere a ciò che non vedi; ",
    category: "Faith",
    source: "Sermons, 43.1",
  },

  // ── Teresa of Ávila ─────────────────────────────────────────────────────────
  {
    id: 6,
    saint: "St. Teresa of Ávila",
    era: "16th century AD",
    born: 1515,
    died: 1582,
    text: "Let nothing disturb you, let nothing frighten you; all things are passing away: God never changes. Patience obtains all things. Whoever has God lacks nothing; God alone suffices.",
    textIt: "Non lasciare che nulla ti turbi, che nulla ti spaventi; ",
    category: "Faith",
    source: "Nada te turbe (poem found in her breviary at death)",
  },
  {
    id: 7,
    saint: "St. Teresa of Ávila",
    era: "16th century AD",
    born: 1515,
    died: 1582,
    text: "Mental prayer in my opinion is nothing else than an intimate sharing between friends; it means taking time frequently to be alone with Him who we know loves us.",
    textIt: "L'orazione mentale secondo me non è altro che un'intima condivisione tra amici; ",
    category: "Prayer",
    source: "Life (Vida), Chapter 8",
  },
  {
    id: 8,
    saint: "St. Teresa of Ávila",
    era: "16th century AD",
    born: 1515,
    died: 1582,
    text: "The important thing is not to think much but to love much; and so do that which best stirs you to love.",
    textIt: "L'importante non è pensare molto ma amare molto; ",
    category: "Love",
    source: "Interior Castle, Fourth Mansion, Chapter 1",
  },
  {
    id: 9,
    saint: "St. Teresa of Ávila",
    era: "16th century AD",
    born: 1515,
    died: 1582,
    text: "God walks among the pots and pipkins.",
    textIt: "Dio cammina tra pentole e vasi.",
    category: "Wisdom",
    source: "Book of Foundations, Chapter 5",
  },

  // ── John of the Cross ───────────────────────────────────────────────────────
  {
    id: 10,
    saint: "St. John of the Cross",
    era: "16th century AD",
    born: 1542,
    died: 1591,
    text: "In the evening of life, we will be judged on love alone.",
    textIt: "Alla sera della vita saremo giudicati solo sull'amore.",
    category: "Love",
    source: "Sayings of Light and Love",
  },
  {
    id: 11,
    saint: "St. John of the Cross",
    era: "16th century AD",
    born: 1542,
    died: 1591,
    text: "Where there is no love, put love, and you will find love.",
    textIt: "Dove non c'è amore, metti amore e troverai amore.",
    category: "Love",
    source: "Letter to María de la Encarnación, July 1591",
  },
  {
    id: 12,
    saint: "St. John of the Cross",
    era: "16th century AD",
    born: 1542,
    died: 1591,
    text: "The soul that is attached to anything, however much good there may be in it, will not arrive at the liberty of divine union.",
    textIt: "L'anima attaccata a qualunque cosa, per quanto bene ci sia in essa, non arriverà alla libertà dell'unione divina.",
    category: "Virtue",
    source: "The Ascent of Mount Carmel, Book I",
  },
  {
    id: 13,
    saint: "St. John of the Cross",
    era: "16th century AD",
    born: 1542,
    died: 1591,
    text: "O Lord, my God, who will seek thee with simple and pure love, and not find that thou art all one can desire?",
    textIt: "O Signore, mio ​​Dio, chi ti cercherà con amore semplice e puro e non scoprirà che sei tutto ciò che si può desiderare?",
    category: "Prayer",
    source: "Sayings of Light and Love",
  },

  // ── Thomas Aquinas ──────────────────────────────────────────────────────────
  {
    id: 14,
    saint: "St. Thomas Aquinas",
    era: "13th century AD",
    born: 1225,
    died: 1274,
    text: "To love is to will the good of another.",
    textIt: "Amare è volere il bene dell'altro.",
    category: "Love",
    source: "Summa Theologiae, I-II, Q.26, Art.4",
  },
  {
    id: 15,
    saint: "St. Thomas Aquinas",
    era: "13th century AD",
    born: 1225,
    died: 1274,
    text: "Three things are necessary for the salvation of man: to know what he ought to believe; to know what he ought to desire; and to know what he ought to do.",
    textIt: "Tre cose sono necessarie per la salvezza dell'uomo: sapere ciò che deve credere; ",
    category: "Wisdom",
    source: "Two Precepts of Charity",
  },
  {
    id: 16,
    saint: "St. Thomas Aquinas",
    era: "13th century AD",
    born: 1225,
    died: 1274,
    text: "Grace does not destroy nature, but perfects it.",
    textIt: "La grazia non distrugge la natura, ma la perfeziona.",
    category: "Faith",
    source: "Summa Theologiae, I, Q.1, Art.8",
  },
  {
    id: 17,
    saint: "St. Thomas Aquinas",
    era: "13th century AD",
    born: 1225,
    died: 1274,
    text: "All that I have written seems like straw compared to what I have seen and what has been revealed to me.",
    textIt: "Tutto quello che ho scritto sembra paglia rispetto a quello che ho visto e che mi è stato rivelato.",
    category: "Humility",
    source: "Reported by Reginald of Piperno (near the end of his life)",
  },

  // ── Thérèse of Lisieux ──────────────────────────────────────────────────────
  {
    id: 18,
    saint: "St. Thérèse of Lisieux",
    era: "19th century AD",
    born: 1873,
    died: 1897,
    text: "My vocation is love!",
    textIt: "La mia vocazione è l'amore!",
    category: "Love",
    source: "Story of a Soul, Manuscript B",
  },
  {
    id: 19,
    saint: "St. Thérèse of Lisieux",
    era: "19th century AD",
    born: 1873,
    died: 1897,
    text: "I will spend my heaven doing good on earth.",
    textIt: "Trascorrerò il mio cielo facendo del bene sulla terra.",
    category: "Hope",
    source: "Last Conversations",
  },
  {
    id: 20,
    saint: "St. Thérèse of Lisieux",
    era: "19th century AD",
    born: 1873,
    died: 1897,
    text: "Without love, deeds, even the most brilliant, count as nothing.",
    textIt: "Senza amore, le azioni, anche le più brillanti, non contano nulla.",
    category: "Love",
    source: "Story of a Soul, Manuscript B",
  },
  {
    id: 21,
    saint: "St. Thérèse of Lisieux",
    era: "19th century AD",
    born: 1873,
    died: 1897,
    text: "I have not given the good God anything but love, and it is with love that He will repay.",
    textIt: "Non ho dato al buon Dio altro che amore, ed è con amore che Egli ripagherà.",
    category: "Love",
    source: "Last Conversations",
  },

  // ── Catherine of Siena ──────────────────────────────────────────────────────
  {
    id: 22,
    saint: "St. Catherine of Siena",
    era: "14th century AD",
    born: 1347,
    died: 1380,
    text: "If you are what you should be, you will set the whole world ablaze!",
    textIt: "Se sei quello che dovresti essere, darai fuoco al mondo intero!",
    category: "Virtue",
    source: "Letters, Letter to Stefano di Corrado Maconi",
  },
  {
    id: 23,
    saint: "St. Catherine of Siena",
    era: "14th century AD",
    born: 1347,
    died: 1380,
    text: "Nothing great is ever achieved without much enduring.",
    textIt: "Non si ottiene mai nulla di grande senza una grande perseveranza.",
    category: "Suffering",
    source: "Letters",
  },
  {
    id: 24,
    saint: "St. Catherine of Siena",
    era: "14th century AD",
    born: 1347,
    died: 1380,
    text: "All the way to heaven is heaven itself, for He said, 'I am the Way.'",
    textIt: "Tutta la strada verso il paradiso è il paradiso stesso, poiché Egli ha detto: 'Io sono la Via'.",
    category: "Hope",
    source: "Letters",
  },
  {
    id: 25,
    saint: "St. Catherine of Siena",
    era: "14th century AD",
    born: 1347,
    died: 1380,
    text: "Drown yourself in the Blood of Christ crucified. There you will find the fire of divine love.",
    textIt: "Annegati nel Sangue di Cristo crocifisso. ",
    category: "Love",
    source: "Letters",
  },

  // ── Bernard of Clairvaux ────────────────────────────────────────────────────
  {
    id: 26,
    saint: "St. Bernard of Clairvaux",
    era: "12th century AD",
    born: 1090,
    died: 1153,
    text: "The measure of love is to love without measure.",
    textIt: "La misura dell'amore è amare senza misura.",
    category: "Love",
    source: "On Loving God (De Diligendo Deo)",
  },
  {
    id: 27,
    saint: "St. Bernard of Clairvaux",
    era: "12th century AD",
    born: 1090,
    died: 1153,
    text: "You will find something far greater in the woods than in books. Stones and trees will teach you what you cannot learn from masters.",
    textIt: "Troverai qualcosa di molto più grande nei boschi che nei libri. ",
    category: "Wisdom",
    source: "Epistola 106",
  },
  {
    id: 28,
    saint: "St. Bernard of Clairvaux",
    era: "12th century AD",
    born: 1090,
    died: 1153,
    text: "I love because I love; I love in order to love.",
    textIt: "Amo perché amo; ",
    category: "Love",
    source: "On Loving God (De Diligendo Deo), Chapter 1",
  },
  {
    id: 29,
    saint: "St. Bernard of Clairvaux",
    era: "12th century AD",
    born: 1090,
    died: 1153,
    text: "Nothing can work me damage except myself; the harm that I sustain I carry about with me, and never am a real sufferer but by my own fault.",
    textIt: "Niente può danneggiarmi tranne me stesso; ",
    category: "Wisdom",
    source: "Epistola 371",
  },

  // ── John Chrysostom ─────────────────────────────────────────────────────────
  {
    id: 30,
    saint: "St. John Chrysostom",
    era: "4th–5th century AD",
    born: 347,
    died: 407,
    text: "No one can harm the man who does not injure himself.",
    textIt: "Nessuno può nuocere all'uomo che non ferisce se stesso.",
    category: "Wisdom",
    source: "Letters, To Olympias",
  },
  {
    id: 31,
    saint: "St. John Chrysostom",
    era: "4th–5th century AD",
    born: 347,
    died: 407,
    text: "The rich man is not one who has much, but one who gives much.",
    textIt: "Il ricco non è chi ha molto, ma chi dà molto.",
    category: "Service",
    source: "Homilies on 2 Corinthians",
  },
  {
    id: 32,
    saint: "St. John Chrysostom",
    era: "4th–5th century AD",
    born: 347,
    died: 407,
    text: "Prayer is the place of refuge for every worry, a foundation for cheerfulness, a source of constant happiness, a protection against sadness.",
    textIt: "La preghiera è il luogo di rifugio per ogni preoccupazione, fondamento dell'allegria, fonte di costante felicità, protezione contro la tristezza.",
    category: "Prayer",
    source: "On the Incomprehensible Nature of God, Homily 5",
  },
  {
    id: 33,
    saint: "St. John Chrysostom",
    era: "4th–5th century AD",
    born: 347,
    died: 407,
    text: "A comprehended god is no god.",
    textIt: "Un dio compreso non è un dio.",
    category: "Faith",
    source: "On the Incomprehensible Nature of God, Homily 1",
  },

  // ── Jerome ──────────────────────────────────────────────────────────────────
  {
    id: 34,
    saint: "St. Jerome",
    era: "4th–5th century AD",
    born: 347,
    died: 420,
    text: "Ignorance of Scripture is ignorance of Christ.",
    textIt: "L’ignoranza della Scrittura è ignoranza di Cristo.",
    category: "Scripture",
    source: "Commentary on Isaiah, Prologue",
  },
  {
    id: 35,
    saint: "St. Jerome",
    era: "4th–5th century AD",
    born: 347,
    died: 420,
    text: "Be ever engaged, so that whenever the devil calls he may find you occupied.",
    textIt: "Siate sempre impegnati, affinché ogni volta che il diavolo vi chiamerà vi trovi occupati.",
    category: "Virtue",
    source: "Letter 125, to Rusticus",
  },
  {
    id: 36,
    saint: "St. Jerome",
    era: "4th–5th century AD",
    born: 347,
    died: 420,
    text: "The friendship that can cease has never been real.",
    textIt: "L'amicizia che può cessare non è mai stata reale.",
    category: "Love",
    source: "Letter 3, to Rufinus",
  },
  {
    id: 37,
    saint: "St. Jerome",
    era: "4th–5th century AD",
    born: 347,
    died: 420,
    text: "Read the divine scriptures constantly; never, indeed, let the sacred volume be out of your hand.",
    textIt: "Leggi costantemente le divine Scritture; ",
    category: "Scripture",
    source: "Letter 125, to Rusticus",
  },

  // ── Francis of Assisi ───────────────────────────────────────────────────────
  {
    id: 38,
    saint: "St. Francis of Assisi",
    era: "12th–13th century AD",
    born: 1181,
    died: 1226,
    text: "What a man is before God, that he is, and no more.",
    textIt: "Ciò che un uomo è davanti a Dio, quello è, e niente di più.",
    category: "Humility",
    source: "Admonitions, 19",
  },
  {
    id: 39,
    saint: "St. Francis of Assisi",
    era: "12th–13th century AD",
    born: 1181,
    died: 1226,
    text: "Where there is charity and wisdom, there is neither fear nor ignorance.",
    textIt: "Dove c’è carità e saggezza, non c’è né paura né ignoranza.",
    category: "Wisdom",
    source: "Admonitions, 27",
  },
  {
    id: 40,
    saint: "St. Francis of Assisi",
    era: "12th–13th century AD",
    born: 1181,
    died: 1226,
    text: "Blessed is the servant who loves his brother as much when he is sick and useless as when he is well and can be of service to him.",
    textIt: "Beato il servo che ama il fratello tanto quando è malato e inutile quanto quando sta bene e può essergli utile.",
    category: "Love",
    source: "Admonitions, 24",
  },
  {
    id: 41,
    saint: "St. Francis of Assisi",
    era: "12th–13th century AD",
    born: 1181,
    died: 1226,
    text: "I have done what was mine to do; may Christ teach you what is yours to do.",
    textIt: "Ho fatto quello che spettava a me fare; ",
    category: "Service",
    source: "Actus Beati Francisci et Sociorum Eius, Chapter 37",
  },

  // ── Francis de Sales ────────────────────────────────────────────────────────
  {
    id: 42,
    saint: "St. Francis de Sales",
    era: "16th–17th century AD",
    born: 1567,
    died: 1622,
    text: "Have patience with all things, but first of all with yourself.",
    textIt: "Abbi pazienza con tutte le cose, ma prima di tutto con te stesso.",
    category: "Virtue",
    source: "Letters, to Madame de Chantal",
  },
  {
    id: 43,
    saint: "St. Francis de Sales",
    era: "16th–17th century AD",
    born: 1567,
    died: 1622,
    text: "Nothing is so strong as gentleness, nothing so gentle as real strength.",
    textIt: "Niente è così forte come la gentilezza, niente è così gentile come la vera forza.",
    category: "Virtue",
    source: "Introduction to the Devout Life",
  },
  {
    id: 44,
    saint: "St. Francis de Sales",
    era: "16th–17th century AD",
    born: 1567,
    died: 1622,
    text: "Do not lose your inner peace for anything whatsoever, even if your whole world seems upset.",
    textIt: "Non perdere la tua pace interiore per nessun motivo, anche se tutto il tuo mondo sembra sconvolto.",
    category: "Prayer",
    source: "Introduction to the Devout Life, Part IV",
  },
  {
    id: 45,
    saint: "St. Francis de Sales",
    era: "16th–17th century AD",
    born: 1567,
    died: 1622,
    text: "Be who you are and be that well.",
    textIt: "Sii quello che sei e sii così bene.",
    category: "Virtue",
    source: "Letters",
  },

  // ── Ignatius of Loyola ──────────────────────────────────────────────────────
  {
    id: 46,
    saint: "St. Ignatius of Loyola",
    era: "15th–16th century AD",
    born: 1491,
    died: 1556,
    text: "Man is created to praise, reverence, and serve God our Lord, and by this means to save his soul.",
    textIt: "L'uomo è creato per lodare, riverire e servire Dio nostro Signore, e in questo modo per salvare la sua anima.",
    category: "Service",
    source: "Spiritual Exercises, Principle and Foundation",
  },
  {
    id: 47,
    saint: "St. Ignatius of Loyola",
    era: "15th–16th century AD",
    born: 1491,
    died: 1556,
    text: "Love ought to manifest itself in deeds rather than in words.",
    textIt: "L'amore dovrebbe manifestarsi nei fatti piuttosto che nelle parole.",
    category: "Love",
    source: "Spiritual Exercises, Contemplation to Attain Love",
  },
  {
    id: 48,
    saint: "St. Ignatius of Loyola",
    era: "15th–16th century AD",
    born: 1491,
    died: 1556,
    text: "Go forth and set the world on fire.",
    textIt: "Vai avanti e dai fuoco al mondo.",
    category: "Faith",
    source: "Letters (Ite, inflammate omnia — traditional attribution)",
  },
  {
    id: 49,
    saint: "St. Ignatius of Loyola",
    era: "15th–16th century AD",
    born: 1491,
    died: 1556,
    text: "There are very few people who realize what God would make of them if they abandoned themselves into his hands, and let themselves be formed by his grace.",
    textIt: "Sono pochissime le persone che si rendono conto di ciò che Dio farebbe di loro se si abbandonassero nelle sue mani e si lasciassero formare dalla sua grazia.",
    category: "Humility",
    source: "Letters",
  },

  // ── Gregory the Great ───────────────────────────────────────────────────────
  {
    id: 50,
    saint: "St. Gregory the Great",
    era: "6th–7th century AD",
    born: 540,
    died: 604,
    text: "The proof of love is in the works. Where love is real, it will do great things. Where it is not, it does nothing.",
    textIt: "La prova dell'amore è in lavorazione. ",
    category: "Service",
    source: "Homilies on the Gospels, Homily 30",
  },
  {
    id: 51,
    saint: "St. Gregory the Great",
    era: "6th–7th century AD",
    born: 540,
    died: 604,
    text: "Holy Scripture is set before the eyes of the mind like a kind of mirror, that we may see our inner face therein.",
    textIt: "La Sacra Scrittura è posta davanti agli occhi della mente come una specie di specchio, affinché possiamo vedervi il nostro volto interiore.",
    category: "Scripture",
    source: "Moralia in Job, Book 2, Dedication",
  },
  {
    id: 52,
    saint: "St. Gregory the Great",
    era: "6th–7th century AD",
    born: 540,
    died: 604,
    text: "One who will not correct small faults will in time fall into greater ones.",
    textIt: "Chi non corregge i piccoli difetti col tempo cadrà in quelli più grandi.",
    category: "Virtue",
    source: "Moralia in Job",
  },
  {
    id: 53,
    saint: "St. Gregory the Great",
    era: "6th–7th century AD",
    born: 540,
    died: 604,
    text: "The higher a man stands in honour, the more humbly should he conduct himself.",
    textIt: "Quanto più un uomo è in alto in onore, tanto più umilmente dovrebbe comportarsi.",
    category: "Humility",
    source: "Pastoral Rule (Regula Pastoralis)",
  },

  // ── Anselm of Canterbury ────────────────────────────────────────────────────
  {
    id: 54,
    saint: "St. Anselm of Canterbury",
    era: "11th–12th century AD",
    born: 1033,
    died: 1109,
    text: "I do not seek to understand in order that I may believe, but I believe in order to understand.",
    textIt: "Non cerco di capire per credere, ma credo per capire.",
    category: "Faith",
    source: "Proslogion, Chapter 1",
  },
  {
    id: 55,
    saint: "St. Anselm of Canterbury",
    era: "11th–12th century AD",
    born: 1033,
    died: 1109,
    text: "God is that than which nothing greater can be conceived.",
    textIt: "Dio è ciò di cui non si può concepire nulla di più grande.",
    category: "Faith",
    source: "Proslogion, Chapter 2",
  },
  {
    id: 56,
    saint: "St. Anselm of Canterbury",
    era: "11th–12th century AD",
    born: 1033,
    died: 1109,
    text: "Lord, I acknowledge and thank thee that thou hast created me in thine image, in order that I may be mindful of thee, may conceive of thee, and love thee.",
    textIt: "Signore, ti riconosco e ti ringrazio che mi hai creato a tua immagine, affinché io mi ricordi di te, possa concepirti e amarti.",
    category: "Prayer",
    source: "Proslogion, Chapter 1",
  },

  // ── Basil the Great ─────────────────────────────────────────────────────────
  {
    id: 57,
    saint: "St. Basil the Great",
    era: "4th century AD",
    born: 329,
    died: 379,
    text: "The bread which you do not use is the bread of the hungry; the garment hanging in your wardrobe is the garment of him who is naked; the shoes that you do not wear are the shoes of the one who is barefoot; the money that you keep locked away is the money of the poor.",
    textIt: "Il pane che non usi è il pane degli affamati; ",
    category: "Service",
    source: "Homily 6 on Luke 12:18",
  },
  {
    id: 58,
    saint: "St. Basil the Great",
    era: "4th century AD",
    born: 329,
    died: 379,
    text: "When someone steals another's clothes, we call them a thief. Should we not give the same name to one who could clothe the naked and does not?",
    textIt: "Quando qualcuno ruba i vestiti di un altro, lo chiamiamo ladro. ",
    category: "Service",
    source: "Homily on 'I Will Pull Down My Barns'",
  },
  {
    id: 59,
    saint: "St. Basil the Great",
    era: "4th century AD",
    born: 329,
    died: 379,
    text: "A good deed is never lost; he who sows courtesy reaps friendship, and he who plants kindness gathers love.",
    textIt: "Una buona azione non è mai perduta; ",
    category: "Virtue",
    source: "Letters",
  },

  // ── Gregory of Nazianzus ────────────────────────────────────────────────────
  {
    id: 60,
    saint: "St. Gregory of Nazianzus",
    era: "4th century AD",
    born: 329,
    died: 390,
    text: "Not to every one does it belong to philosophize about God; it is the occupation of those who have examined themselves carefully and have been students of meditation.",
    textIt: "Non a tutti spetta filosofare su Dio; ",
    category: "Wisdom",
    source: "Oration 27 (First Theological Oration)",
  },
  {
    id: 61,
    saint: "St. Gregory of Nazianzus",
    era: "4th century AD",
    born: 329,
    died: 390,
    text: "The scope of our art is to provide the soul with wings, to rescue it from the world and give it to God, and to watch over that which is in His image.",
    textIt: "Lo scopo della nostra arte è quello di fornire le ali all'anima, di salvarla dal mondo e donarla a Dio, e di vegliare su ciò che è a Sua immagine.",
    category: "Service",
    source: "Oration 2 (Apologia)",
  },
  {
    id: 62,
    saint: "St. Gregory of Nazianzus",
    era: "4th century AD",
    born: 329,
    died: 390,
    text: "What God is in His nature and essence, no man ever yet has discovered or can discover.",
    textIt: "Ciò che Dio è nella Sua natura ed essenza, nessun uomo ha ancora scoperto o può scoprire.",
    category: "Faith",
    source: "Oration 28 (Second Theological Oration)",
  },

  // ── Ambrose of Milan ────────────────────────────────────────────────────────
  {
    id: 63,
    saint: "St. Ambrose of Milan",
    era: "4th century AD",
    born: 340,
    died: 397,
    text: "No one heals himself by wounding another.",
    textIt: "Nessuno guarisce se stesso ferendo un altro.",
    category: "Wisdom",
    source: "On the Duties of the Clergy (De Officiis Ministrorum)",
  },
  {
    id: 64,
    saint: "St. Ambrose of Milan",
    era: "4th century AD",
    born: 340,
    died: 397,
    text: "Faith is the foundation of all justice; for we believe what we cannot see, and in this faith the mind finds rest.",
    textIt: "La fede è il fondamento di ogni giustizia; ",
    category: "Faith",
    source: "On the Death of Valentinian",
  },
  {
    id: 65,
    saint: "St. Ambrose of Milan",
    era: "4th century AD",
    born: 340,
    died: 397,
    text: "Let your door stand open to receive him, unlock your soul to him, offer him a welcome in your mind, and then you will see the riches of simplicity, the treasures of peace, the joy of grace.",
    textIt: "Lascia che la tua porta sia aperta per riceverlo, aprigli la tua anima, offrigli il benvenuto nella tua mente, e allora vedrai le ricchezze della semplicità, i tesori della pace, la gioia della grazia.",
    category: "Hope",
    source: "On the Sacraments (De Sacramentis)",
  },

  // ── Benedict of Nursia ──────────────────────────────────────────────────────
  {
    id: 66,
    saint: "St. Benedict of Nursia",
    era: "5th–6th century AD",
    born: 480,
    died: 547,
    text: "Listen carefully, my son, to the master's instructions, and attend to them with the ear of your heart.",
    textIt: "Ascolta attentamente, figlio mio, le istruzioni del maestro e presta attenzione ad esse con l'orecchio del tuo cuore.",
    category: "Wisdom",
    source: "Rule of St. Benedict, Prologue",
  },
  {
    id: 67,
    saint: "St. Benedict of Nursia",
    era: "5th–6th century AD",
    born: 480,
    died: 547,
    text: "Prefer nothing to the love of Christ.",
    textIt: "Non anteporre nulla all'amore di Cristo.",
    category: "Love",
    source: "Rule of St. Benedict, Chapter 72",
  },
  {
    id: 68,
    saint: "St. Benedict of Nursia",
    era: "5th–6th century AD",
    born: 480,
    died: 547,
    text: "Idleness is the enemy of the soul; and therefore the brethren ought to be employed in manual labor at certain times, at others, in devout reading.",
    textIt: "L'ozio è nemico dell'anima; ",
    category: "Virtue",
    source: "Rule of St. Benedict, Chapter 48",
  },

  // ── John Vianney ────────────────────────────────────────────────────────────
  {
    id: 69,
    saint: "St. John Vianney",
    era: "18th–19th century AD",
    born: 1786,
    died: 1859,
    text: "The priesthood is the love of the heart of Jesus.",
    textIt: "Il sacerdozio è l'amore del cuore di Gesù.",
    category: "Love",
    source: "Catechism on the Priesthood",
  },
  {
    id: 70,
    saint: "St. John Vianney",
    era: "18th–19th century AD",
    born: 1786,
    died: 1859,
    text: "Prayer is to our soul what rain is to the soil. Fertilize the soil ever so richly, it will remain barren unless fed by frequent rains.",
    textIt: "La preghiera è per la nostra anima ciò che la pioggia è per la terra. ",
    category: "Prayer",
    source: "Sermons and Catechetical Instructions",
  },
  {
    id: 71,
    saint: "St. John Vianney",
    era: "18th–19th century AD",
    born: 1786,
    died: 1859,
    text: "Tell God all that is in your heart, as one unloads one's heart, its pleasures and its pains, to a dear friend.",
    textIt: "Racconta a Dio tutto quello che hai nel cuore, come si scarica il proprio cuore, i suoi piaceri e i suoi dolori, a un caro amico.",
    category: "Prayer",
    source: "Sermons and Catechetical Instructions",
  },

  // ── Patrick ─────────────────────────────────────────────────────────────────
  {
    id: 72,
    saint: "St. Patrick",
    era: "5th century AD",
    born: 385,
    died: 461,
    text: "I am Patrick, a sinner, most unlearned, the least of all the faithful, and utterly despised by many.",
    textIt: "Io sono Patrizio, un peccatore, il più ignorante, l'ultimo di tutti i fedeli e assolutamente disprezzato da molti.",
    category: "Humility",
    source: "Confessio, Chapter 1",
  },
  {
    id: 73,
    saint: "St. Patrick",
    era: "5th century AD",
    born: 385,
    died: 461,
    text: "I used to pray many times a day. More and more did the love of God, and my fear of him and faith increase, and my spirit was moved so that in a single day I would say as many as a hundred prayers.",
    textIt: "Pregavo molte volte al giorno. ",
    category: "Prayer",
    source: "Confessio, Chapter 16",
  },

  // ── Faustina Kowalska ───────────────────────────────────────────────────────
  {
    id: 74,
    saint: "St. Faustina Kowalska",
    era: "20th century AD",
    born: 1905,
    died: 1938,
    text: "Jesus, I trust in You.",
    textIt: "Gesù, confido in Te.",
    category: "Faith",
    source: "Diary: Divine Mercy in My Soul",
  },
  {
    id: 75,
    saint: "St. Faustina Kowalska",
    era: "20th century AD",
    born: 1905,
    died: 1938,
    text: "Love and suffering go together; I can see that very well in the life of the saints.",
    textIt: "Amore e sofferenza vanno insieme; ",
    category: "Suffering",
    source: "Diary: Divine Mercy in My Soul",
  },
  {
    id: 76,
    saint: "St. Faustina Kowalska",
    era: "20th century AD",
    born: 1905,
    died: 1938,
    text: "O my God, I am aware of Your Majesty, and I tremble; but I am also aware of Your mercy and goodness, and I take courage.",
    textIt: "O mio Dio, conosco la Tua Maestà e tremo; ",
    category: "Prayer",
    source: "Diary: Divine Mercy in My Soul",
  },

  // ── Teresa of Calcutta ──────────────────────────────────────────────────────
  {
    id: 77,
    saint: "St. Teresa of Calcutta",
    era: "20th century AD",
    born: 1910,
    died: 1997,
    text: "Not all of us can do great things. But we can do small things with great love.",
    textIt: "Non tutti possiamo fare grandi cose. ",
    category: "Service",
    source: "Speeches and Writings",
  },
  {
    id: 78,
    saint: "St. Teresa of Calcutta",
    era: "20th century AD",
    born: 1910,
    died: 1997,
    text: "If you judge people, you have no time to love them.",
    textIt: "Se giudichi le persone, non hai tempo per amarle.",
    category: "Love",
    source: "Speeches and Writings",
  },
  {
    id: 79,
    saint: "St. Teresa of Calcutta",
    era: "20th century AD",
    born: 1910,
    died: 1997,
    text: "The fruit of silence is prayer; the fruit of prayer is faith; the fruit of faith is love; the fruit of love is service; the fruit of service is peace.",
    textIt: "Il frutto del silenzio è la preghiera; ",
    category: "Prayer",
    source: "Speeches and Writings",
  },

  // ── Maximilian Kolbe ────────────────────────────────────────────────────────
  {
    id: 80,
    saint: "St. Maximilian Kolbe",
    era: "20th century AD",
    born: 1894,
    died: 1941,
    text: "The most deadly poison of our times is indifference.",
    textIt: "Il veleno più mortale dei nostri tempi è l’indifferenza.",
    category: "Virtue",
    source: "Writings and Conferences",
  },
  {
    id: 81,
    saint: "St. Maximilian Kolbe",
    era: "20th century AD",
    born: 1894,
    died: 1941,
    text: "No one in the world can alter Truth. What we can do and should do is to seek truth and to serve it when we have found it.",
    textIt: "Nessuno al mondo può alterare la Verità. ",
    category: "Wisdom",
    source: "Writings and Conferences",
  },

  // ── Thomas More ─────────────────────────────────────────────────────────────
  {
    id: 82,
    saint: "St. Thomas More",
    era: "15th–16th century AD",
    born: 1478,
    died: 1535,
    text: "I am the king's good servant, but God's first.",
    textIt: "Sono il buon servitore del re, ma prima di tutto di Dio.",
    category: "Faith",
    source: "Attributed as last words before execution, 1535",
  },
  {
    id: 83,
    saint: "St. Thomas More",
    era: "15th–16th century AD",
    born: 1478,
    died: 1535,
    text: "The things, good Lord, that I pray for, give me the grace to labor for.",
    textIt: "Le cose per le quali prego, buon Dio, mi danno la grazia di lavorare.",
    category: "Prayer",
    source: "A Godly Meditation",
  },

  // ── Ignatius of Antioch ─────────────────────────────────────────────────────
  {
    id: 84,
    saint: "St. Ignatius of Antioch",
    era: "1st–2nd century AD",
    born: 35,
    died: 108,
    text: "I am God's wheat, and let me be ground by the teeth of wild beasts that I may be found pure bread of Christ.",
    textIt: "Io sono il grano di Dio e lasciami macinare dai denti delle bestie selvagge affinché possa essere trovato pane puro di Cristo.",
    category: "Suffering",
    source: "Letter to the Romans, Chapter 4",
  },
  {
    id: 85,
    saint: "St. Ignatius of Antioch",
    era: "1st–2nd century AD",
    born: 35,
    died: 108,
    text: "Permit me to be an imitator of the passion of my God.",
    textIt: "Permettimi di essere imitatore della passione del mio Dio.",
    category: "Suffering",
    source: "Letter to the Romans, Chapter 6",
  },
  {
    id: 86,
    saint: "St. Ignatius of Antioch",
    era: "1st–2nd century AD",
    born: 35,
    died: 108,
    text: "It is not that I want merely to be called a Christian, but actually to be one.",
    textIt: "Non è che io voglia semplicemente essere chiamato cristiano, ma esserlo realmente.",
    category: "Virtue",
    source: "Letter to the Romans, Chapter 3",
  },

  // ── Bonaventure ─────────────────────────────────────────────────────────────
  {
    id: 87,
    saint: "St. Bonaventure",
    era: "13th century AD",
    born: 1221,
    died: 1274,
    text: "Whoever is not illumined by such great splendors of created things is blind; whoever is not awakened by such great outcries is deaf; whoever does not praise God because of all these effects is dumb.",
    textIt: "Chi non è illuminato da sì grandi splendori delle cose create è cieco; ",
    category: "Wisdom",
    source: "The Soul's Journey into God (Itinerarium Mentis in Deum), Chapter 1",
  },
  {
    id: 88,
    saint: "St. Bonaventure",
    era: "13th century AD",
    born: 1221,
    died: 1274,
    text: "No knowledge is sufficient for salvation except the knowledge of Jesus Christ, and him crucified.",
    textIt: "Nessuna conoscenza è sufficiente per la salvezza tranne la conoscenza di Gesù Cristo e di lui crocifisso.",
    category: "Faith",
    source: "The Soul's Journey into God (Itinerarium Mentis in Deum), Prologue",
  },

  // ── Anthony of Padua ────────────────────────────────────────────────────────
  {
    id: 89,
    saint: "St. Anthony of Padua",
    era: "12th–13th century AD",
    born: 1195,
    died: 1231,
    text: "The Scriptures are the heart of God given to us in letters.",
    textIt: "Le Scritture sono il cuore di Dio donatoci nelle lettere.",
    category: "Scripture",
    source: "Sermons for Sundays and Festivals",
  },
  {
    id: 90,
    saint: "St. Anthony of Padua",
    era: "12th–13th century AD",
    born: 1195,
    died: 1231,
    text: "Actions speak louder than words; let your words teach and your actions speak.",
    textIt: "Le azioni parlano più forte delle parole; ",
    category: "Service",
    source: "Sermons for Sundays and Festivals",
  },

  // ── Vincent de Paul ─────────────────────────────────────────────────────────
  {
    id: 91,
    saint: "St. Vincent de Paul",
    era: "16th–17th century AD",
    born: 1581,
    died: 1660,
    text: "It is our duty to prefer the service of the poor to everything else, and to offer such service as quickly as possible.",
    textIt: "È nostro dovere preferire il servizio ai poveri a tutto il resto e offrirlo il più rapidamente possibile.",
    category: "Service",
    source: "Letters and Conferences of St. Vincent de Paul",
  },
  {
    id: 92,
    saint: "St. Vincent de Paul",
    era: "16th–17th century AD",
    born: 1581,
    died: 1660,
    text: "The poor are our masters, and we must serve them as such.",
    textIt: "I poveri sono i nostri padroni e come tali dobbiamo servirli.",
    category: "Service",
    source: "Letters and Conferences of St. Vincent de Paul",
  },

  // ── Joan of Arc ─────────────────────────────────────────────────────────────
  {
    id: 93,
    saint: "St. Joan of Arc",
    era: "15th century AD",
    born: 1412,
    died: 1431,
    text: "I am not afraid; I was born to do this.",
    textIt: "Non ho paura; ",
    category: "Faith",
    source: "Trial Testimony, Rouen, 1431",
  },
  {
    id: 94,
    saint: "St. Joan of Arc",
    era: "15th century AD",
    born: 1412,
    died: 1431,
    text: "I would rather die than do something which I know to be a sin, or to be against God's will.",
    textIt: "Preferirei morire piuttosto che fare qualcosa che so essere un peccato o che è contro la volontà di Dio.",
    category: "Virtue",
    source: "Trial Testimony, Rouen, 1431",
  },

  // ── Dominic ─────────────────────────────────────────────────────────────────
  {
    id: 95,
    saint: "St. Dominic",
    era: "12th–13th century AD",
    born: 1170,
    died: 1221,
    text: "Speak only with God or of God.",
    textIt: "Parla solo con Dio o di Dio.",
    category: "Prayer",
    source: "Jordan of Saxony, Libellus de Principiis Ordinis Praedicatorum",
  },
  {
    id: 96,
    saint: "St. Dominic",
    era: "12th–13th century AD",
    born: 1170,
    died: 1221,
    text: "Arm yourself with prayer rather than a sword; wear humility rather than fine clothes.",
    textIt: "Armatevi di preghiera piuttosto che di spada; ",
    category: "Prayer",
    source: "Early Dominican sources, attributed",
  },

  // ── Leo the Great ───────────────────────────────────────────────────────────
  {
    id: 97,
    saint: "St. Leo the Great",
    era: "5th century AD",
    born: 400,
    died: 461,
    text: "Christian, acknowledge your dignity and, now made a sharer of the divine nature, refuse to return to the old baseness by degenerate conduct.",
    textIt: "Cristiano, riconosci la tua dignità e, reso ormai partecipe della natura divina, rifiuta di ritornare all'antica bassezza con una condotta degenerata.",
    category: "Virtue",
    source: "Sermons, 1.3 (On the Nativity of the Lord)",
  },
  {
    id: 98,
    saint: "St. Leo the Great",
    era: "5th century AD",
    born: 400,
    died: 461,
    text: "Without detriment to the properties of either nature, majesty took on humility, strength took on weakness, eternity took on mortality.",
    textIt: "Senza pregiudizio delle proprietà dell'una o dell'altra natura, la maestà ha assunto l'umiltà, la forza ha assunto la debolezza, l'eternità ha assunto la mortalità.",
    category: "Humility",
    source: "Tome of Leo (Epistola 28 ad Flavianum)",
  },
  {
    id: 99,
    saint: "St. Leo the Great",
    era: "5th century AD",
    born: 400,
    died: 461,
    text: "In Jesus Christ there is neither confusion of natures nor division of person.",
    textIt: "In Gesù Cristo non c'è né confusione di nature né divisione di persona.",
    category: "Faith",
    source: "Tome of Leo (Epistola 28 ad Flavianum)",
  },

  // ── Cyprian of Carthage ─────────────────────────────────────────────────────
  {
    id: 100,
    saint: "St. Cyprian of Carthage",
    era: "3rd century AD",
    born: 200,
    died: 258,
    text: "He cannot have God for his Father, who has not the Church for his mother.",
    textIt: "Non può avere Dio per Padre chi non ha la Chiesa per madre.",
    category: "Faith",
    source: "On the Unity of the Catholic Church, Chapter 6",
  },
  {
    id: 101,
    saint: "St. Cyprian of Carthage",
    era: "3rd century AD",
    born: 200,
    died: 258,
    text: "Our prayer is public and common; and when we pray, we pray not for one, but for the whole people, because we the whole people are one.",
    textIt: "La nostra preghiera è pubblica e comune; ",
    category: "Prayer",
    source: "On the Lord's Prayer, Chapter 8",
  },

  // ── Irenaeus of Lyons ───────────────────────────────────────────────────────
  {
    id: 102,
    saint: "St. Irenaeus of Lyons",
    era: "2nd century AD",
    born: 130,
    died: 202,
    text: "The glory of God is man fully alive; and the life of man is the vision of God.",
    textIt: "La gloria di Dio è l'uomo pienamente vivo; ",
    category: "Hope",
    source: "Against Heresies, Book IV, Chapter 20",
  },
  {
    id: 103,
    saint: "St. Irenaeus of Lyons",
    era: "2nd century AD",
    born: 130,
    died: 202,
    text: "For this is why the Word became man, and the Son of God became the Son of man: so that man, by entering into communion with the Word and thus receiving divine sonship, might become a son of God.",
    textIt: "Per questo infatti il ​​Verbo si è fatto uomo, e il Figlio di Dio si è fatto Figlio dell'uomo: affinché l'uomo, entrando in comunione con il Verbo e ricevendo così la filiazione divina, diventasse figlio di Dio.",
    category: "Faith",
    source: "Against Heresies, Book III, Chapter 19",
  },

  // ── Alphonsus Liguori ───────────────────────────────────────────────────────
  {
    id: 104,
    saint: "St. Alphonsus Liguori",
    era: "17th–18th century AD",
    born: 1696,
    died: 1787,
    text: "He who prays is saved; he who prays not is lost.",
    textIt: "Chi prega è salvato; ",
    category: "Prayer",
    source: "The Great Means of Salvation and Perfection",
  },
  {
    id: 105,
    saint: "St. Alphonsus Liguori",
    era: "17th–18th century AD",
    born: 1696,
    died: 1787,
    text: "The greatest gift that a soul can give to God is to abandon itself entirely to His holy will, and to have a perfect conformity with it.",
    textIt: "Il dono più grande che un'anima può fare a Dio è abbandonarsi interamente alla sua santa volontà e avere una perfetta conformità ad essa.",
    category: "Prayer",
    source: "The Practice of the Love of Jesus Christ",
  },

  // ── Hildegard of Bingen ─────────────────────────────────────────────────────
  {
    id: 106,
    saint: "St. Hildegard of Bingen",
    era: "11th–12th century AD",
    born: 1098,
    died: 1179,
    text: "All living creatures are, so to speak, sparks from the radiation of God's brilliance, and these sparks emerge from God like the rays of the sun.",
    textIt: "Tutte le creature viventi sono, per così dire, scintille provenienti dall'irradiazione dello splendore di Dio, e queste scintille emergono da Dio come i raggi del sole.",
    category: "Wisdom",
    source: "Scivias",
  },
  {
    id: 107,
    saint: "St. Hildegard of Bingen",
    era: "11th–12th century AD",
    born: 1098,
    died: 1179,
    text: "I am a feather on the breath of God.",
    textIt: "Sono una piuma sul respiro di Dio.",
    category: "Humility",
    source: "Writings and Letters (attributed)",
  },

  // ── Philip Neri ─────────────────────────────────────────────────────────────
  {
    id: 108,
    saint: "St. Philip Neri",
    era: "16th century AD",
    born: 1515,
    died: 1595,
    text: "Cheerfulness strengthens the heart and makes us persevere in a good life; therefore the servant of God ought always to be in good spirits.",
    textIt: "L'allegria fortifica il cuore e ci fa perseverare nella buona vita; ",
    category: "Hope",
    source: "Sayings of St. Philip Neri",
  },
  {
    id: 109,
    saint: "St. Philip Neri",
    era: "16th century AD",
    born: 1515,
    died: 1595,
    text: "Cast yourself into the arms of God and be very sure that if he wants anything of you, He will fit you for the work and give you strength.",
    textIt: "Gettati tra le braccia di Dio e sii molto sicuro che se vuole qualcosa da te, ti adatterà al lavoro e ti darà la forza.",
    category: "Hope",
    source: "Sayings of St. Philip Neri",
  },

  // ── Polycarp of Smyrna ──────────────────────────────────────────────────────
  {
    id: 110,
    saint: "St. Polycarp of Smyrna",
    era: "1st–2nd century AD",
    born: 69,
    died: 155,
    text: "Eighty and six years have I served him, and He never did me any injury: how then can I blaspheme my King and my Savior?",
    textIt: "L'ho servito ottantasei anni, e non mi ha mai fatto alcun male: come dunque potrei bestemmiare il mio Re e il mio Salvatore?",
    category: "Faith",
    source: "Martyrdom of Polycarp, Chapter 9",
  },
  // ── New Additions ──────────────────────────────────────────────────────
  {
    id: 111,
    saint: "St. Barnabas",
    era: "1st century AD",
    born: 1,
    died: 61,
    text: "A good man, full of the Holy Spirit and of faith.",
    textIt: "Un uomo buono, pieno di Spirito Santo e di fede.",
    category: "Faith",
    source: "Acts 11:24"
  },
  {
    id: 112,
    saint: "St. Michael the Archangel",
    era: "Angelic",
    born: null,
    died: null,
    text: "Who is like God?",
    textIt: "Chi è come Dio?",
    category: "Spiritual Warfare",
    source: "Tradition (Archangel's name)"
  },
  {
    id: 113,
    saint: "St. John Bosco",
    era: "19th century AD",
    born: 1815,
    died: 1888,
    text: "Run, jump, have all the fun you want at the right time, but, for heaven's sake, do not commit sin!",
    textIt: "Correte, saltate, divertitevi quanto volete al momento giusto, ma, per l'amor del cielo, non commettete peccato!",
    category: "Virtue",
    source: "Advice to boys"
  },
  {
    id: 114,
    saint: "St. John Bosco",
    era: "19th century AD",
    born: 1815,
    died: 1888,
    text: "Do not put off till tomorrow the good you can do today.",
    textIt: "Non rimandare a domani il bene che puoi fare oggi.",
    category: "Action",
    source: "Maxims"
  }
];